name: Build and test

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '.bumpversion.cfg'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/build.yml'
      # re-include used workflow calls
      - '!.github/workflows/build-workflow-call.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.7', '3.8', '3.9', '3.10']
    
    name: Test - Python ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install test dependencies
        run: pip install tox tox-gh-actions
      - name: Launch tests
        run: tox

  dist:
    needs: [test]
    name: Build sdist/wheel
    uses: ./.github/workflows/build-workflow-call.yml
    with:
      artifact-name: example-dist

  dist_check:
    needs: [dist]
    runs-on: ubuntu-latest
    
    name: Post-build checks
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          pip install twine
      - name: Retrieve packages
        uses: actions/download-artifact@v3
        with:
          name: example-dist
          path: dist
      - name: twine check
        run: twine check --strict dist/*
