name: Build/Test/Deploy

on:
  push:
    branches:
    - "*"
  release:
    types: [created, published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
    
    name: Test - Python ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install test dependencies
        run: pip install tox
      - name: Launch tests
        run: tox -e py

  dist:
    needs: [test]
    runs-on: ubuntu-latest

    name: Build sdist/wheel
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build packages
        run: flit build
      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pydiamond-dist
          path: dist

  dist_check:
    needs: [dist]
    runs-on: ubuntu-latest
    
    name: Post-build checks
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          pip install twine
      - name: Retrieve packages
        uses: actions/download-artifact@v3
        with:
          name: pydiamond-dist
          path: dist
      - name: twine check
        run: twine check --strict dist/*

  dist_upload:
    if: github.event_name == 'release'
    needs: [dist, dist_check]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    name: Distribute packages
    steps:
      - name: Retrieve packages
        uses: actions/download-artifact@v3
        with:
          name: pydiamond-dist
          path: dist
      - name: Upload to Github Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: dist/*
