name: Lint/Format

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.py'
  push:
    branch:
      - main
    paths:
      - '**.py'
      # include current file
      - '.github/workflows/lint-format.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PROJECT_CONFIG: ${{ github.workspace }}/pyproject.toml
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mypy pytest
      - name: Format check (black)
        uses: psf/black@stable
        with:
          options: '--check --diff --config=${{ env.PROJECT_CONFIG }}'
      - name: Format check (isort)
        uses: isort/isort-action@v1.0.0
        if: always()
        with:
          configuration: '--check-only --diff --settings-file=$PROJECT_CONFIG'
      - name: Static type hinting check
        if: always()
        run: mypy --non-interactive --install-types --config-file=$PROJECT_CONFIG .
