name: Lint/Format

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**.py"
      - "requirements*.txt"
      - "pyproject.toml"
  push:
    branch:
      - main
    paths:
      - "**.py"

jobs:
  check_needed:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_run.outputs.should_skip }}

    name: Verify if checks are needed
    steps:
      - name: Skip run check
        id: skip_run
        if: github.event_name == 'pull_request'
        uses: fkirc/skip-duplicate-actions@v4
        with:
          paths: '["**.py"]'

  lint_format_check:
    needs: [check_needed]
    if: ${{ needs.check_needed.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    name: Lint/Format check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mypy black isort
      - name: Format check
        run: |
          black --check --diff ${{ github.workspace }}
          isort --check --diff ${{ github.workspace }}
      - name: Static type hinting check
        if: always()
        run: mypy --non-interactive --install-types ${{ github.workspace }}