name: Fetch all repo branches

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch origin
      - run: git branch --list
      - run: git branch --remote --list
